version: "3.8"

services:
    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./backend:/var/www/html
        depends_on:
            - app
            - frontend

    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: react_frontend
        restart: always
        environment:
            NODE_ENV: production
        ports:
            - "5173:80"

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
