# Use Node.js official image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the frontend source code
COPY . .

# Build the production files
RUN npm run build


# Expose a port (for Vite if needed)
EXPOSE 5173

